In [ ]:
import pandas as pd
import numpy as np

df1 = pd.read_stata('datasampel/01 KEPESERTAAN 260819.dta')

df4 = pd.read_stata('datasampel/04 FKRTL 260819.dta')

df5 = pd.read_stata('datasampel/05 FKRTL Diagnosis Sekunder 260819.dta')

In [1]:
df4['FKL11'].value_counts()

NameError: name 'df4' is not defined

### **Join Data FKRTL dengan Diagnosis Sekunder**

Integrasi Data FKRTL dengan Diagnosis Sekunder

In [2]:
sekunder = df5.groupby('FKL02')['FKL24_A'].apply(list).reset_index(name='Kode dan Nama Diagnosis Sekunder')

In [76]:
fkrtl = pd.merge(df4, sekunder, on= 'FKL02', how='left')
# fkrtl_sekunder

In [77]:
# drop feature yang tidak digunakan
fkrtl.drop(['PSTV02', 'PSTV15', 'FKL33',
               'FKL34', 'FKL35', 'FKL36', 'FKL37', 'FKL38', 'FKL39',
               'FKL40', 'FKL41', 'FKL42', 'FKL43', 'FKL44', 'FKL45',
               'FKL46'], axis=1, inplace=True)
# 'FKL16', 'FKL16A', 'FKL18', 'FKL18A'

In [78]:
# Hasil join dengan indikator left_only
options = ['BUKAN RUJUKAN'] 

# selecting rows based on condition 
tidak_dirujuk = fkrtl[fkrtl['FKL25'].isin(options)]
# tidak_dirujuk

In [79]:
tidak_dirujuk['Hasil Rujukan FKTP?'] = 'No'

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [80]:
tidak_dirujuk['provinsi perujuk sama?'] = 0
tidak_dirujuk['kab/kota perujuk sama?'] = 0

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [101]:
# Hasil join dengan indikator left_only
options = ['BUKAN RUJUKAN'] 

# selecting rows based on condition 
dirujuk = fkrtl[~fkrtl['FKL25'].isin(options)]
dirujuk

,PSTV01,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,FKL08,FKL09,FKL10,...,FKL31,FKL32,FKL47,FKL48,Kode dan Nama Diagnosis Sekunder,Hasil Rujukan FKTP?,provinsi perujuk sama?,kab/kota perujuk sama?,compare1,compare2
2134,222638,1761107150004416,2015-07-28,2015-07-28,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,181400.0,181400,181400,NaN,Yes,NaN,1.0,False,True
2135,222638,1761107150004108,2015-07-29,2015-08-03,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,2540200.0,2540200,2540200,NaN,Yes,NaN,1.0,False,True
7116,748559,1761112160004670,2016-12-22,2016-12-22,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,267200.0,267200,267200,NaN,Yes,NaN,1.0,False,True
13229,1438815,1761108160000477,2016-08-02,2016-08-02,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,166800.0,166800,166800,NaN,Yes,NaN,1.0,False,True
14341,1566666,1761110160005183,2016-10-26,2016-10-26,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,318200.0,318200,318200,NaN,Yes,NaN,1.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906899,104461783,238205150000337,2015-05-12,2015-05-12,NUSA TENGGARA TIMUR,KAB. FLORES TIMUR,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 5,161000.0,161000,161000,"[I10 Essential (primary) hypertension, K12 Sto...",Yes,NaN,0.0,False,False
906901,104496251,2973907160002712,2016-07-01,2016-07-01,DKI JAKARTA,KOTA JAKARTA SELATAN,PEMERINTAH PROVINSI,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 1,179700.0,179700,179700,NaN,Yes,NaN,0.0,False,False
906902,149413026,3426912160002670,2016-12-29,2016-12-29,KALIMANTAN TIMUR,KAB. BERAU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 4,524300.0,524300,524300,NaN,Yes,NaN,0.0,False,False
906903,173692605,1945511160000001,2016-11-01,2016-11-05,RIAU,KAB. BENGKALIS,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,4060500.0,4060500,4060500,NaN,Yes,NaN,0.0,False,False
906904,202929480,3660507160001027,2016-07-28,2016-07-28,LAMPUNG,KAB. WAY KANAN,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,240600.0,240600,240600,NaN,Yes,NaN,0.0,False,False

In [102]:
dirujuk['Hasil Rujukan FKTP?'] = 'Yes'

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [103]:
dirujuk['compare1'] = dirujuk['FKL06'].isin(dirujuk['FKL25'])
dirujuk['compare2'] = dirujuk['FKL07'].isin(dirujuk['FKL26'])

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [113]:
dirujuk['provinsi perujuk sama?'] = 0

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [114]:
dirujuk

,PSTV01,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,FKL08,FKL09,FKL10,...,FKL31,FKL32,FKL47,FKL48,Kode dan Nama Diagnosis Sekunder,Hasil Rujukan FKTP?,provinsi perujuk sama?,kab/kota perujuk sama?,compare1,compare2
2134,222638,1761107150004416,2015-07-28,2015-07-28,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,181400.0,181400,181400,NaN,Yes,0,1.0,False,True
2135,222638,1761107150004108,2015-07-29,2015-08-03,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,2540200.0,2540200,2540200,NaN,Yes,0,1.0,False,True
7116,748559,1761112160004670,2016-12-22,2016-12-22,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,267200.0,267200,267200,NaN,Yes,0,1.0,False,True
13229,1438815,1761108160000477,2016-08-02,2016-08-02,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,166800.0,166800,166800,NaN,Yes,0,1.0,False,True
14341,1566666,1761110160005183,2016-10-26,2016-10-26,BALI,KAB. GIANYAR,MISSING,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,318200.0,318200,318200,NaN,Yes,0,1.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906899,104461783,238205150000337,2015-05-12,2015-05-12,NUSA TENGGARA TIMUR,KAB. FLORES TIMUR,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 5,161000.0,161000,161000,"[I10 Essential (primary) hypertension, K12 Sto...",Yes,0,0.0,False,False
906901,104496251,2973907160002712,2016-07-01,2016-07-01,DKI JAKARTA,KOTA JAKARTA SELATAN,PEMERINTAH PROVINSI,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 1,179700.0,179700,179700,NaN,Yes,0,0.0,False,False
906902,149413026,3426912160002670,2016-12-29,2016-12-29,KALIMANTAN TIMUR,KAB. BERAU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 4,524300.0,524300,524300,NaN,Yes,0,0.0,False,False
906903,173692605,1945511160000001,2016-11-01,2016-11-05,RIAU,KAB. BENGKALIS,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,4060500.0,4060500,4060500,NaN,Yes,0,0.0,False,False
906904,202929480,3660507160001027,2016-07-28,2016-07-28,LAMPUNG,KAB. WAY KANAN,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,240600.0,240600,240600,NaN,Yes,0,0.0,False,False

In [115]:
# Hasil join dengan indikator left_only
options = [True] 

# selecting rows based on condition 
dirujuk1 = dirujuk[dirujuk['compare2'].isin(options)]
dirujuk1['kab/kota perujuk sama?'] = 1

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [116]:
# selecting rows based on condition 
dirujuk2 = dirujuk[~dirujuk['compare2'].isin(options)]
dirujuk2['kab/kota perujuk sama?'] = 0

C:\Users\WIN10\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [134]:
frames = [tidak_dirujuk, dirujuk1, dirujuk2]

fkrtl = pd.concat(frames)

In [135]:
fkrtl

,PSTV01,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,FKL08,FKL09,FKL10,...,FKL31,FKL32,FKL47,FKL48,Kode dan Nama Diagnosis Sekunder,Hasil Rujukan FKTP?,provinsi perujuk sama?,kab/kota perujuk sama?,compare1,compare2
0,15,109501160002166,2016-01-30,2016-02-02,SULAWESI TENGAH,KAB. TOLI TOLI,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 3,1567100.0,1567100,1567100,NaN,No,0,0,NaN,NaN
47,340,3185408160009536,2016-08-18,2016-08-31,DKI JAKARTA,KOTA JAKARTA BARAT,VERTIKAL/PUSAT,RUMAH SAKIT,KHUSUS KANKER ONKOLOGI,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 1,20740600.0,20740600,20740600,[D63 Anaemia in chronic diseases classified el...,No,0,0,NaN,NaN
60,3062,1582902160041210,2016-02-23,2016-03-01,DKI JAKARTA,KOTA JAKARTA PUSAT,VERTIKAL/PUSAT,RUMAH SAKIT,RS KELAS A,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 1,3432700.0,3432700,3432700,[Z38 Liveborn infants according to place of bi...,No,0,0,NaN,NaN
97,7228,3376710160002187,2016-10-11,2016-10-14,JAWA BARAT,KOTA TASIKMALAYA,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 1,4826600.0,4826600,4826600,[O42 Premature rupture of membranes],No,0,0,NaN,NaN
103,8731,3594211160002831,2016-11-28,2016-11-30,NUSA TENGGARA BARAT,KAB. DOMPU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,1245400.0,1245400,1245400,"[O30 Multiple gestation, O32 Maternal care for...",No,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906899,104461783,238205150000337,2015-05-12,2015-05-12,NUSA TENGGARA TIMUR,KAB. FLORES TIMUR,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 5,161000.0,161000,161000,"[I10 Essential (primary) hypertension, K12 Sto...",Yes,0,0,False,False
906901,104496251,2973907160002712,2016-07-01,2016-07-01,DKI JAKARTA,KOTA JAKARTA SELATAN,PEMERINTAH PROVINSI,RUMAH SAKIT,RS KELAS B,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 1,179700.0,179700,179700,NaN,Yes,0,0,False,False
906902,149413026,3426912160002670,2016-12-29,2016-12-29,KALIMANTAN TIMUR,KAB. BERAU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 4,524300.0,524300,524300,NaN,Yes,0,0,False,False
906903,173692605,1945511160000001,2016-11-01,2016-11-05,RIAU,KAB. BENGKALIS,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,REGIONAL 2,4060500.0,4060500,4060500,NaN,Yes,0,0,False,False
906904,202929480,3660507160001027,2016-07-28,2016-07-28,LAMPUNG,KAB. WAY KANAN,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT JALAN TINGKAT LANJUT,...,REGIONAL 2,240600.0,240600,240600,NaN,Yes,0,0,False,False

#### **Mengubah tipe data dan format tanggal dan Membuat Atribut Turunan Yaitu Lama Kunjungan**

In [136]:
fkrtl['fkrtl-tanggal datang'] = pd.to_datetime(fkrtl['FKL03'])
fkrtl['fkrtl-tanggal pulang'] = pd.to_datetime(fkrtl['FKL04'])


fkrtl['fkrtl-tanggal datang'] = fkrtl['fkrtl-tanggal datang'].dt.date
fkrtl['fkrtl-tanggal pulang'] = fkrtl['fkrtl-tanggal pulang'].dt.date

In [137]:
fkrtl['fkrtl-Lama Kunjungan'] = fkrtl['fkrtl-tanggal pulang'] -  fkrtl['fkrtl-tanggal datang']

In [138]:
fkrtl['fkrtl-Lama Kunjungan'] = pd.to_numeric(fkrtl['fkrtl-Lama Kunjungan'].dt.days, downcast='integer')

In [139]:
fkrtl['fkrtl-Lama Kunjungan'] = fkrtl['fkrtl-Lama Kunjungan'] + 1

**Membuat atribut turunan yaitu hari melakukan kunjungan**

In [140]:
import datetime as dt
fkrtl['fkrtl-tanggal datang'] = pd.to_datetime(fkrtl['fkrtl-tanggal datang'], errors='coerce')

fkrtl['fkrtl-Hari Kunjungan'] = fkrtl['fkrtl-tanggal datang'].dt.day_name()
fkrtl.head()

,PSTV01,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,FKL08,FKL09,FKL10,...,Kode dan Nama Diagnosis Sekunder,Hasil Rujukan FKTP?,provinsi perujuk sama?,kab/kota perujuk sama?,compare1,compare2,fkrtl-tanggal datang,fkrtl-tanggal pulang,fkrtl-Lama Kunjungan,fkrtl-Hari Kunjungan
0,15,109501160002166,2016-01-30,2016-02-02,SULAWESI TENGAH,KAB. TOLI TOLI,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,NaN,No,0,0,NaN,NaN,2016-01-30,2016-02-02,4,Saturday
47,340,3185408160009536,2016-08-18,2016-08-31,DKI JAKARTA,KOTA JAKARTA BARAT,VERTIKAL/PUSAT,RUMAH SAKIT,KHUSUS KANKER ONKOLOGI,RAWAT INAP TINGKAT LANJUT,...,[D63 Anaemia in chronic diseases classified el...,No,0,0,NaN,NaN,2016-08-18,2016-08-31,14,Thursday
60,3062,1582902160041210,2016-02-23,2016-03-01,DKI JAKARTA,KOTA JAKARTA PUSAT,VERTIKAL/PUSAT,RUMAH SAKIT,RS KELAS A,RAWAT INAP TINGKAT LANJUT,...,[Z38 Liveborn infants according to place of bi...,No,0,0,NaN,NaN,2016-02-23,2016-03-01,8,Tuesday
97,7228,3376710160002187,2016-10-11,2016-10-14,JAWA BARAT,KOTA TASIKMALAYA,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,[O42 Premature rupture of membranes],No,0,0,NaN,NaN,2016-10-11,2016-10-14,4,Tuesday
103,8731,3594211160002831,2016-11-28,2016-11-30,NUSA TENGGARA BARAT,KAB. DOMPU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,"[O30 Multiple gestation, O32 Maternal care for...",No,0,0,NaN,NaN,2016-11-28,2016-11-30,3,Monday

In [141]:
fkrtl['fkrtl-Weekend?'] = np.where(fkrtl['fkrtl-Hari Kunjungan'].isin(['Sunday','Saturday']),1,0)

**Membuat atribut turunan yaitu bulan saat melakuan kunjungan**

In [142]:
fkrtl['fkrtl-Month'] = fkrtl['fkrtl-tanggal datang'].dt.month

**Membuat atribut turunan yaitu Tahun saat melakuan kunjungan**

In [143]:
fkrtl['fkrtl-Year'] = fkrtl['fkrtl-tanggal datang'].dt.year

**Membuat atribut turunan yaitu Quarter saat melakuan kunjungan**

In [144]:
fkrtl['fkrtl-Quarter'] = fkrtl['fkrtl-tanggal datang'].dt.quarter

In [145]:
fkrtl.head()

,PSTV01,FKL02,FKL03,FKL04,FKL05,FKL06,FKL07,FKL08,FKL09,FKL10,...,compare1,compare2,fkrtl-tanggal datang,fkrtl-tanggal pulang,fkrtl-Lama Kunjungan,fkrtl-Hari Kunjungan,fkrtl-Weekend?,fkrtl-Month,fkrtl-Year,fkrtl-Quarter
0,15,109501160002166,2016-01-30,2016-02-02,SULAWESI TENGAH,KAB. TOLI TOLI,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,NaN,NaN,2016-01-30,2016-02-02,4,Saturday,1,1,2016,1
47,340,3185408160009536,2016-08-18,2016-08-31,DKI JAKARTA,KOTA JAKARTA BARAT,VERTIKAL/PUSAT,RUMAH SAKIT,KHUSUS KANKER ONKOLOGI,RAWAT INAP TINGKAT LANJUT,...,NaN,NaN,2016-08-18,2016-08-31,14,Thursday,0,8,2016,3
60,3062,1582902160041210,2016-02-23,2016-03-01,DKI JAKARTA,KOTA JAKARTA PUSAT,VERTIKAL/PUSAT,RUMAH SAKIT,RS KELAS A,RAWAT INAP TINGKAT LANJUT,...,NaN,NaN,2016-02-23,2016-03-01,8,Tuesday,0,2,2016,1
97,7228,3376710160002187,2016-10-11,2016-10-14,JAWA BARAT,KOTA TASIKMALAYA,SWASTA,RUMAH SAKIT,RS SWASTA SETARA TYPE C,RAWAT INAP TINGKAT LANJUT,...,NaN,NaN,2016-10-11,2016-10-14,4,Tuesday,0,10,2016,4
103,8731,3594211160002831,2016-11-28,2016-11-30,NUSA TENGGARA BARAT,KAB. DOMPU,PEMERINTAH KABUPATEN/KOTA,RUMAH SAKIT,RS KELAS C,RAWAT INAP TINGKAT LANJUT,...,NaN,NaN,2016-11-28,2016-11-30,3,Monday,0,11,2016,4

In [146]:
fkrtl['Nomor Peserta'] = fkrtl['PSTV01'].astype('category')
fkrtl['FKRTL-ID Kunjungan'] = fkrtl['FKL02']
fkrtl['FKRTL-Provinsi Faskes'] = fkrtl['FKL05']
fkrtl['FKRTL-Kab/Kota Faskes'] = fkrtl['FKL06']
fkrtl['FKRTL-Kepemilikan Faskes'] = fkrtl['FKL07']
fkrtl['FKRTL-Jenis Faskes'] = fkrtl['FKL08']
fkrtl['FKRTL-Tipe Faskes'] = fkrtl['FKL09']

fkrtl['FKRTL-Tingkat Layanan'] = fkrtl['FKL10']
fkrtl['FKRTL-Segmen Peserta'] =fkrtl['FKL12']
fkrtl['FKRTL-Kelas Rawat'] = fkrtl['FKL13']
fkrtl['FKRTL-Status Pulang'] = fkrtl['FKL14']
fkrtl['FKRTL-Kode dan Nama Diagnosis Masuk'] = fkrtl['FKL15']
fkrtl['FKRTL-Kode dan Nama Diagnosis Sekunder'] = fkrtl['Kode dan Nama Diagnosis Sekunder']
fkrtl['FKRTL-Kode dan Nama Diagnosis Primer'] = fkrtl['FKL17']

fkrtl['FKRTL-Biaya Tagih'] = fkrtl['FKL47']
fkrtl['FKRTL-Biaya Verifikasi'] = fkrtl['FKL48']

fkrtl['FKRTL-Provinsi Faskes Perujuk'] = fkrtl['FKL25']
fkrtl['FKRTL-Kab/Kota Faskes Perujuk'] = fkrtl['FKL26']
fkrtl['FKRTL-Kepemilikan Faskes Perujuk'] = fkrtl['FKL27']
fkrtl['FKRTL-Jenis Faskes Perujuk'] = fkrtl['FKL28']
fkrtl['FKRTL-Tipe Faskes Perujuk'] = fkrtl['FKL29']

In [147]:
fkrtl.drop(['PSTV01', 'FKL02', 'FKL03', 'FKL04', 'FKL05', 'FKL06', 'FKL07', 'FKL08', 'FKL09', 'FKL10', 'FKL11', 'FKL12', 'FKL13', 'FKL14', 'FKL15', 'FKL16',
            'FKL16A', 'FKL17', 'FKL18', 'FKL18A', 'FKL19', 'FKL19A', 'FKL20', 'FKL21', 'FKL22', 'FKL23', 'FKL25', 'FKL26', 'FKL27', 'FKL28', 'FKL29', 'FKL30',
            'FKL31', 'FKL32', 'FKL47', 'FKL48', 'compare1', 'compare2', 'Kode dan Nama Diagnosis Sekunder'], axis=1, inplace=True)

In [148]:
fkrtl.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 906905 entries, 0 to 906904
Data columns (total 32 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   Hasil Rujukan FKTP?                     906905 non-null  object
 1   provinsi perujuk sama?                  906905 non-null  int64
 2   kab/kota perujuk sama?                  906905 non-null  int64
 3   fkrtl-tanggal datang                    906905 non-null  datetime64[ns]
 4   fkrtl-tanggal pulang                    906905 non-null  object
 5   fkrtl-Lama Kunjungan                    906905 non-null  int16
 6   fkrtl-Hari Kunjungan                    906905 non-null  object
 7   fkrtl-Weekend?                          906905 non-null  int32
 8   fkrtl-Month                             906905 non-null  int64
 9   fkrtl-Year                              906905 non-null  int64
 10  fkrtl-Quarter                           906905 non-null  int64
 11  Nomor Peserta                           906905 non-null  category
 12  FKRTL-ID Kunjungan                      906905 non-null  object
 13  FKRTL-Provinsi Faskes                   906905 non-null  category
 14  FKRTL-Kab/Kota Faskes                   906905 non-null  category
 15  FKRTL-Kepemilikan Faskes                906905 non-null  category
 16  FKRTL-Jenis Faskes                      906905 non-null  category
 17  FKRTL-Tipe Faskes                       906905 non-null  category
 18  FKRTL-Tingkat Layanan                   906905 non-null  category
 19  FKRTL-Segmen Peserta                    906905 non-null  category
 20  FKRTL-Kelas Rawat                       906905 non-null  category
 21  FKRTL-Status Pulang                     906905 non-null  category
 22  FKRTL-Kode dan Nama Diagnosis Masuk     906905 non-null  category
 23  FKRTL-Kode dan Nama Diagnosis Sekunder  517274 non-null  object
 24  FKRTL-Kode dan Nama Diagnosis Primer    906905 non-null  category
 25  FKRTL-Biaya Tagih                       906905 non-null  int32
 26  FKRTL-Biaya Verifikasi                  906905 non-null  int32
 27  FKRTL-Provinsi Faskes Perujuk           906905 non-null  category
 28  FKRTL-Kab/Kota Faskes Perujuk           906905 non-null  category
 29  FKRTL-Kepemilikan Faskes Perujuk        906905 non-null  category
 30  FKRTL-Jenis Faskes Perujuk              906905 non-null  category
 31  FKRTL-Tipe Faskes Perujuk               906905 non-null  category
dtypes: category(17), datetime64[ns](1), int16(1), int32(3), int64(5), object(5)
memory usage: 127.9+ MB

### **Menggabung data kunjungan dengan data Kepesertaan**

In [149]:
# import pandas as pd
# df = pd.read_csv('/content/drive/MyDrive/final_data.csv')
# df1 = pd.read_stata('/content/drive/MyDrive/TA-02 /Data Sampel BPJS/01 KEPESERTAAN 260819.dta')

data_peserta = df1[['PSTV01', 'PSTV03', 'PSTV04', 'PSTV05', 'PSTV06', 'PSTV07', 'PSTV08', 'PSTV11',
                    'PSTV12', 'PSTV13', 'PSTV14']]
fkrtl = pd.merge(fkrtl, data_peserta, left_on='Nomor Peserta', right_on='PSTV01', how='left')

In [150]:
fkrtl['Hubungan Keluarga'] = fkrtl['PSTV04']
fkrtl['Status Kawin'] = fkrtl['PSTV06']
fkrtl['Kelas Rawat Peserta'] = fkrtl['PSTV07']
fkrtl['Jenis Kelamin Peserta'] = fkrtl['PSTV05']
fkrtl['Segmen Peserta yang Terdaftar'] = fkrtl['PSTV08']
fkrtl['Kepemilikan Faskes yang Terdaftar'] = fkrtl['PSTV11']
fkrtl['Jenis Faskes yang Terdaftar'] = fkrtl['PSTV12']
fkrtl['Provinsi Peserta Terdaftar'] = fkrtl['PSTV13']
fkrtl['Kab/Kota Peserta Terdaftar'] = fkrtl['PSTV14']

fkrtl['Umur'] = fkrtl['fkrtl-tanggal datang'] -  fkrtl['PSTV03']
fkrtl['Umur'] = (fkrtl["Umur"] / np.timedelta64(1, 'Y')).astype('int')

In [152]:
fkrtl.drop(['PSTV01', 'PSTV03', 'PSTV04', 'PSTV05','PSTV06', 'PSTV07', 'PSTV08', 'PSTV11',
                    'PSTV12', 'PSTV13', 'PSTV14'], axis=1, inplace=True)

**Buat Kategori Umur Menurut WHO**

bayi = dibawah 1 tahun
 
anak-anak = 2-10 tahun.
 
remaja  = 11-19 tahun.

dewasa = 20-60 tahun.

lanjut usia = diatas 60 tahun

In [153]:
conditions = [
              (fkrtl['Umur'] <= 1),
              (fkrtl['Umur'] >= 2) & (fkrtl['Umur'] <= 10),
              (fkrtl['Umur'] >= 11) & (fkrtl['Umur'] <= 19),
              (fkrtl['Umur'] >= 20) & (fkrtl['Umur'] <= 60),
              (fkrtl['Umur'] > 60)]

values = ['bayi', 'anak-anak', 'remaja', 'dewasa', 'lanjut usia']

fkrtl['kategori umur'] = np.select(conditions, values)

In [154]:
# check missing value
total = fkrtl.isnull().sum().sort_values(ascending=False)

percent = (fkrtl.isnull().sum()/fkrtl.isnull().count()) \
.sort_values(ascending=False)

missing_data = pd.concat([total, percent], axis=1, \
                        keys=['Total', 'Missing Percent'])

missing_data['Missing Percent'] = \
missing_data['Missing Percent'].apply(lambda x: x*100)

missing_data.loc[missing_data['Missing Percent']>= 0]

                                         Total  Missing Percent
FKRTL-Kode dan Nama Diagnosis Sekunder  389631        42.962714
kategori umur                                0         0.000000
FKRTL-Kelas Rawat                            0         0.000000
FKRTL-Tingkat Layanan                        0         0.000000
FKRTL-Tipe Faskes                            0         0.000000
FKRTL-Jenis Faskes                           0         0.000000
FKRTL-Kepemilikan Faskes                     0         0.000000
FKRTL-Kab/Kota Faskes                        0         0.000000
FKRTL-Provinsi Faskes                        0         0.000000
FKRTL-ID Kunjungan                           0         0.000000
Nomor Peserta                                0         0.000000
fkrtl-Quarter                                0         0.000000
fkrtl-Year                                   0         0.000000
fkrtl-Month                                  0         0.000000
fkrtl-Weekend?                               0         0.000000
fkrtl-Hari Kunjungan                         0         0.000000
fkrtl-Lama Kunjungan                         0         0.000000
fkrtl-tanggal pulang                         0         0.000000
fkrtl-tanggal datang                         0         0.000000
kab/kota perujuk sama?                       0         0.000000
provinsi perujuk sama?                       0         0.000000
FKRTL-Segmen Peserta                         0         0.000000
FKRTL-Status Pulang                          0         0.000000
Umur                                         0         0.000000
FKRTL-Kode dan Nama Diagnosis Masuk          0         0.000000
Kab/Kota Peserta Terdaftar                   0         0.000000
Provinsi Peserta Terdaftar                   0         0.000000
Jenis Faskes yang Terdaftar                  0         0.000000
Kepemilikan Faskes yang Terdaftar            0         0.000000
Segmen Peserta yang Terdaftar                0         0.000000
Jenis Kelamin Peserta                        0         0.000000
Kelas Rawat Peserta                          0         0.000000
Status Kawin                                 0         0.000000
Hubungan Keluarga                            0         0.000000
FKRTL-Tipe Faskes Perujuk                    0         0.000000
FKRTL-Jenis Faskes Perujuk                   0         0.000000
FKRTL-Kepemilikan Faskes Perujuk             0         0.000000
FKRTL-Kab/Kota Faskes Perujuk                0         0.000000
FKRTL-Provinsi Faskes Perujuk                0         0.000000
FKRTL-Biaya Verifikasi                       0         0.000000
FKRTL-Biaya Tagih                            0         0.000000
FKRTL-Kode dan Nama Diagnosis Primer         0         0.000000
Hasil Rujukan FKTP?                          0         0.000000

In [155]:
fkrtl.to_csv('datasampel/fkrtl_not_transform.csv')

## **Label Encoding / Data Transfomation**

In [156]:
from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
fkrtl['FKRTL-Segmen Peserta'].replace(to_replace=['BUKAN PEKERJA', 'PBI APBN', 'PBI APBD', 'PBPU', 'PPU', 'MISSING'], value=[1, 2, 3, 4, 5, 0], inplace=True)
fkrtl['Segmen Peserta yang Terdaftar'].replace(to_replace=['Bukan pekerja', 'PBI APBN', 'PBI APBD', 'PBPU', 'PPU', 'MISSING'], value=[1, 2, 3, 4, 5, 0], inplace=True)

fkrtl['FKRTL-Jenis Faskes Perujuk'].replace(to_replace=['PUSKESMAS', 'KLINIK PRATAMA', 'KLINIK PERTAMA', 'DOKTER UMUM', 'KLINIK UTAMA', 'DOKTER GIGI', 'LABORATORIUM', 'RUMAH SAKIT', 'LAIN-LAIN', 'APOTIK', 'OPTIK', 'BUKAN RUJUKAN', 'PEMERINTAH', 'PMI', 'MISSING'], value=[1, 2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 0], inplace=True)
fkrtl['Jenis Faskes yang Terdaftar'].replace(to_replace=['Puskesmas', 'Klinik Pratama', 'Dokter Umum'], value=[1, 2, 3], inplace=True)
fkrtl['FKRTL-Jenis Faskes'].replace(to_replace=['RUMAH SAKIT', 'KLINIK UTAMA', 'KLINIK PRATAMA'], value=[1, 2, 3], inplace=True)
fkrtl['Hubungan Keluarga'].replace(to_replace=['Peserta', 'Suami', 'Istri', 'Anak', 'Tambahan'], value=[1, 2, 3, 4, 5], inplace=True)
fkrtl['Status Kawin'].replace(to_replace=['BELUM KAWIN', 'KAWIN', 'CERAI', 'TIDAK TERDEFINISI'], value =[1, 2, 3, 4], inplace=True)

fkrtl['Jenis Kelamin Peserta'].replace(to_replace=['LAKI-LAKI', 'PEREMPUAN'], value =[1, 2], inplace=True)
fkrtl['Kelas Rawat Peserta'].replace(to_replace=['KELAS I', 'KELAS II', 'KELAS III', 'MISSING'], value =[1, 2, 3, 0], inplace=True)
fkrtl['FKRTL-Kelas Rawat'].replace(to_replace=['KELAS I', 'KELAS II', 'KELAS III', 'MISSING'], value =[1, 2, 3, 0], inplace=True)

fkrtl['Kepemilikan Faskes yang Terdaftar'].replace(to_replace=['VERTIKAL/PUSAT', 'PEMERINTAH PROVINSI', 'PEMERINTAH KABUPATEN/KOTA', 'POLRI', 'TNI AD', 'TNI AL', 'TNI AU', 'BUMN', 'SWASTA', 'MISSING'], value =[1, 2, 3, 4, 5, 6, 7, 8, 9, 0], inplace=True)
fkrtl['FKRTL-Kepemilikan Faskes Perujuk'].replace(to_replace=['VERTIKAL/PUSAT', 'PEMERINTAH PROVINSI', 'PEMERINTAH KABUPATEN/KOTA', 'POLRI', 'TNI AD', 'TNI AL', 'TNI AU', 'BUMN', 'SWASTA', 'BUKAN RUJUKAN', 'MISSING'], value =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0], inplace=True)
fkrtl['FKRTL-Kepemilikan Faskes'].replace(to_replace=['VERTIKAL/PUSAT', 'PEMERINTAH PROVINSI', 'PEMERINTAH KABUPATEN/KOTA', 'POLRI', 'TNI AD', 'TNI AL', 'TNI AU', 'BUMN', 'SWASTA', 'BUKAN RUJUKAN', 'MISSING'], value =[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0], inplace=True)

fkrtl['FKRTL-Tipe Faskes'] = labelencoder.fit_transform(fkrtl['FKRTL-Tipe Faskes'].astype(str))
fkrtl['FKRTL-Tipe Faskes Perujuk'] = labelencoder.fit_transform(fkrtl['FKRTL-Tipe Faskes Perujuk'].astype(str))

fkrtl['Provinsi Peserta Terdaftar'] = labelencoder.fit_transform(fkrtl['Provinsi Peserta Terdaftar'].astype(str))
fkrtl['FKRTL-Provinsi Faskes Perujuk'] = labelencoder.fit_transform(fkrtl['FKRTL-Provinsi Faskes Perujuk'].astype(str))
fkrtl['FKRTL-Provinsi Faskes'] = labelencoder.fit_transform(fkrtl['FKRTL-Provinsi Faskes'].astype(str))

fkrtl['FKRTL-Kab/Kota Faskes'] = labelencoder.fit_transform(fkrtl['FKRTL-Kab/Kota Faskes'].astype(str))
fkrtl['FKRTL-Kab/Kota Faskes Perujuk'] = labelencoder.fit_transform(fkrtl['FKRTL-Kab/Kota Faskes Perujuk'].astype(str))
fkrtl['Kab/Kota Peserta Terdaftar'] = labelencoder.fit_transform(fkrtl['Kab/Kota Peserta Terdaftar'].astype(str))

fkrtl['FKRTL-Tingkat Layanan'].replace(to_replace=['RAWAT JALAN TINGKAT LANJUT', 'RAWAT INAP TINGKAT LANJUT'], value =[1, 2], inplace=True)
fkrtl['FKRTL-Status Pulang'].replace(to_replace=['SEHAT', 'RUJUK', 'MENINGGAL', 'PULANG PAKSA', 'TIDAK TAHUN', 'MISSING'], value =[1, 2, 3, 4, 5, 0], inplace=True)

fkrtl['FKRTL-Kode dan Nama Diagnosis Masuk'] = labelencoder.fit_transform(fkrtl['FKRTL-Kode dan Nama Diagnosis Masuk'].astype(str))
fkrtl['FKRTL-Kode dan Nama Diagnosis Primer'] = labelencoder.fit_transform(fkrtl['FKRTL-Kode dan Nama Diagnosis Primer'].astype(str))

fkrtl['FKRTL-ID Kunjungan'] = labelencoder.fit_transform(fkrtl['FKRTL-ID Kunjungan'].astype(str))

fkrtl['fkrtl-Hari Kunjungan'].replace(to_replace=['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], value =[1, 2, 3, 4, 5, 6, 7], inplace=True)
fkrtl['fkrtl-Year'].replace(to_replace=[2015, 2016], value =[1, 2], inplace=True)

fkrtl['kategori umur'].replace(to_replace=['bayi', 'anak-anak', 'remaja', 'dewasa', 'lanjut usia'], value =[1, 2, 3, 4, 5], inplace=True)


fkrtl['Hasil Rujukan FKTP?'].replace(to_replace=['Yes', 'No'], value =[1, 0], inplace=True)

In [157]:
fkrtl.to_csv('datasampel/fkrtl_transformation.csv')