In [8]:
import pandas as pd
import numpy as np

df = pd.read_csv('datasampel/fkrtl_transformation.csv')
df2 = pd.read_csv('datasampel/fkrtl_not_transform.csv')

In [24]:
df2.drop(['Hasil Rujukan FKTP?', 'Unnamed: 0', 'FKRTL-ID Kunjungan', 'Nomor Peserta', 'fkrtl-tanggal datang', 'fkrtl-tanggal pulang', 'Segmen Peserta yang Terdaftar', 'Kepemilikan Faskes yang Terdaftar', 
         'Jenis Faskes yang Terdaftar', 'Provinsi Peserta Terdaftar', 'Kab/Kota Peserta Terdaftar', 'FKRTL-Kab/Kota Faskes', 'FKRTL-Kode dan Nama Diagnosis Sekunder', 'FKRTL-Provinsi Faskes Perujuk', 'FKRTL-Kab/Kota Faskes Perujuk', 'FKRTL-Kepemilikan Faskes Perujuk', 'FKRTL-Jenis Faskes Perujuk', 'FKRTL-Tipe Faskes Perujuk', 'FKRTL-Provinsi Faskes'], axis=1, inplace=True)

In [25]:
df2.drop(['Umur', 'fkrtl-Quarter', 'fkrtl-Year', 'fkrtl-Month', 'fkrtl-Lama Kunjungan', 'FKRTL-Biaya Verifikasi', 'FKRTL-Biaya Tagih', 'fkrtl-Weekend?', 'FKRTL-Kode dan Nama Diagnosis Masuk',
        'FKRTL-Kode dan Nama Diagnosis Primer', 'Jenis Kelamin Peserta', 'provinsi perujuk sama?', 'kab/kota perujuk sama?'], axis=1, inplace=True)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 906905 entries, 0 to 906904
Data columns (total 12 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   fkrtl-Hari Kunjungan      906905 non-null  int64
 1   FKRTL-Kepemilikan Faskes  906905 non-null  int64
 2   FKRTL-Jenis Faskes        906905 non-null  int64
 3   FKRTL-Tipe Faskes         906905 non-null  int64
 4   FKRTL-Tingkat Layanan     906905 non-null  int64
 5   FKRTL-Segmen Peserta      906905 non-null  int64
 6   FKRTL-Kelas Rawat         906905 non-null  int64
 7   FKRTL-Status Pulang       906905 non-null  int64
 8   Hubungan Keluarga         906905 non-null  int64
 9   Status Kawin              906905 non-null  int64
 10  Kelas Rawat Peserta       906905 non-null  int64
 11  kategori umur             906905 non-null  int64
dtypes: int64(12)
memory usage: 83.0 MB

### One Hot Encoder

In [12]:
from sklearn.preprocessing import OneHotEncoder

y = OneHotEncoder(sparse=False)
y = y.fit_transform(df)
df_y = pd.DataFrame(y, index=df.index)
df_y

,0,1,2,3,4,5,6,7,8,9,...,74,75,76,77,78,79,80,81,82,83
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
906900,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
906901,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
906902,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
906903,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
906904,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

### get dummies

In [26]:
# Get dummies
X = pd.get_dummies(df2, prefix_sep='_', drop_first=True)
# X head
X.head()

,fkrtl-Hari Kunjungan_Monday,fkrtl-Hari Kunjungan_Saturday,fkrtl-Hari Kunjungan_Sunday,fkrtl-Hari Kunjungan_Thursday,fkrtl-Hari Kunjungan_Tuesday,fkrtl-Hari Kunjungan_Wednesday,FKRTL-Kepemilikan Faskes_MISSING,FKRTL-Kepemilikan Faskes_PEMERINTAH KABUPATEN/KOTA,FKRTL-Kepemilikan Faskes_PEMERINTAH PROVINSI,FKRTL-Kepemilikan Faskes_POLRI,...,Status Kawin_CERAI,Status Kawin_KAWIN,Status Kawin_TIDAK TERDEFINISI,Kelas Rawat Peserta_KELAS II,Kelas Rawat Peserta_KELAS III,Kelas Rawat Peserta_MISSING,kategori umur_bayi,kategori umur_dewasa,kategori umur_lanjut usia,kategori umur_remaja
0,0,1,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
2,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,0,0,0,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
4,1,0,0,0,0,0,0,1,0,0,...,0,0,1,0,1,0,0,1,0,0

In [21]:
df1 = pd.read_csv('datasampel/fkrtl_transformation.csv')
df1.drop(['Unnamed: 0', 'FKRTL-ID Kunjungan', 'Nomor Peserta', 'fkrtl-tanggal datang', 'fkrtl-tanggal pulang', 'Segmen Peserta yang Terdaftar', 'Kepemilikan Faskes yang Terdaftar', 
         'Jenis Faskes yang Terdaftar', 'Provinsi Peserta Terdaftar', 'Kab/Kota Peserta Terdaftar'], axis=1, inplace=True)

df_numerik = df1[['Umur', 'fkrtl-Quarter', 'fkrtl-Year', 'fkrtl-Month', 'fkrtl-Lama Kunjungan', 'FKRTL-Biaya Verifikasi', 'FKRTL-Biaya Tagih', 'fkrtl-Weekend?', 'FKRTL-Kode dan Nama Diagnosis Masuk',
        'FKRTL-Kode dan Nama Diagnosis Primer', 'Jenis Kelamin Peserta', 'provinsi perujuk sama?', 'kab/kota perujuk sama?']]

In [22]:
#Concatenate the two dataframes : 
data_out = pd.concat([df_y, df_numerik], axis=1)

In [27]:
data_out2 = pd.concat([X, df_numerik], axis=1)

In [29]:
data_out.to_csv('datasampel/one_hot_fkrtl.csv')

In [30]:
data_out2.to_csv('datasampel/one_hot_fkrtl_get_dummies.csv')