In [19]:
import pandas as pd
import numpy as np

# df = pd.read_csv('datasampel/fktp_transformation.csv')
df2 = pd.read_csv('datasampel/fktp_not_transformation.csv')

In [20]:
df2.drop(['Unnamed: 0', 'ID Kunjungan', 'Nomor Peserta', 'FKTP-tanggal datang', 'FKTP-tanggal pulang', 'Segmen Peserta yang Terdaftar', 'Kepemilikan Faskes yang Terdaftar', 
         'Jenis Faskes yang Terdaftar', 'Provinsi Peserta Terdaftar', 'Kab/Kota Peserta Terdaftar', 'FKTP-Kab/Kota Faskes Rujukan', 'FKTP-Kab/Kota Faskes', 'FKTP-Provinsi Faskes Rujukan', 'FKTP-Kab/Kota Faskes Rujukan', 'FKTP-Kepemilikan Faskes Rujukan', 'FKTP-Jenis Faskes Rujukan',
        'FKTP-Jenis Kunjungan', 'FKTP-Poli Faskes Rujukan', 'FKTP-Provinsi Faskes'], axis=1, inplace=True)

In [21]:
df2.drop(['Umur', 'FKTP-Quarter', 'FKTP-Year', 'FKTP-Month', 'FKTP-Lama Kunjungan', 'FKTP-Biaya Verifikasi', 'FKTP-Biaya Tagih', 'Non-Kapitasi?', 'Kapitasi?', 'Dirujuk?', 'Jumlah Tindakan Non-Kapitasi', 'provinsi rujukan sama?', 'kab/kota rujukan sama?', 'FKTP-Weekend?', 'FKTP-Kode dan Nama Diagnosis', 'Jenis Kelamin Peserta'], axis=1, inplace=True)

In [22]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1733755 entries, 0 to 1733754
Data columns (total 13 columns):
 #   Column                    Dtype
---  ------                    -----
 0   FKTP-Kepemilikan Faskes   object
 1   FKTP-Jenis Faskes         object
 2   FKTP-Tipe Faskes          object
 3   FKTP-Tingkat Layanan      object
 4   FKTP-Poli                 object
 5   FKTP-Segmen Peserta       object
 6   FKTP-Status Pulang        object
 7   FKTP-Tipe Faskes Rujukan  object
 8   FKTP-Hari Kunjungan       object
 9   Hubungan Keluarga         object
 10  Status Kawin              object
 11  Kelas Rawat Peserta       object
 12  kategori umur             object
dtypes: object(13)
memory usage: 172.0+ MB

In [15]:
from sklearn.preprocessing import OneHotEncoder

y = OneHotEncoder(sparse=False)
y = y.fit_transform(df)
df_y = pd.DataFrame(y, index=df.index)
df_y

,0,1,2,3,4,5,6,7,8,9,...,112,113,114,115,116,117,118,119,120,121
0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1733750,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1733751,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1733752,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1733753,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1733754,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0

In [23]:
# Get dummies
X = pd.get_dummies(df2, prefix_sep='_', drop_first=True)
# X head
X.head()

,FKTP-Kepemilikan Faskes_MISSING,FKTP-Kepemilikan Faskes_PEMERINTAH KABUPATEN/KOTA,FKTP-Kepemilikan Faskes_PEMERINTAH PROVINSI,FKTP-Kepemilikan Faskes_POLRI,FKTP-Kepemilikan Faskes_SWASTA,FKTP-Kepemilikan Faskes_TNI AD,FKTP-Kepemilikan Faskes_TNI AL,FKTP-Kepemilikan Faskes_TNI AU,FKTP-Kepemilikan Faskes_VERTIKAL/PUSAT,FKTP-Jenis Faskes_DOKTER UMUM,...,Status Kawin_CERAI,Status Kawin_KAWIN,Status Kawin_TIDAK TERDEFINISI,Kelas Rawat Peserta_KELAS II,Kelas Rawat Peserta_KELAS III,Kelas Rawat Peserta_MISSING,kategori umur_bayi,kategori umur_dewasa,kategori umur_lanjut usia,kategori umur_remaja
0,0,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
2,0,1,0,0,0,0,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0

In [24]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1733755 entries, 0 to 1733754
Columns: 109 entries, FKTP-Kepemilikan Faskes_MISSING to kategori umur_remaja
dtypes: uint8(109)
memory usage: 180.2 MB

In [16]:
df1 = pd.read_csv('datasampel/fktp_transformation.csv')
# df1.drop(['Unnamed: 0', 'ID Kunjungan', 'Nomor Peserta', 'FKTP-tanggal datang', 'FKTP-tanggal pulang', 'Segmen Peserta yang Terdaftar', 'Kepemilikan Faskes yang Terdaftar', 
#          'Jenis Faskes yang Terdaftar', 'Provinsi Peserta Terdaftar', 'Kab/Kota Peserta Terdaftar'], axis=1, inplace=True)

df_numerik = df1[['Umur', 'FKTP-Quarter', 'FKTP-Year', 'FKTP-Month', 'FKTP-Lama Kunjungan', 'FKTP-Biaya Verifikasi', 'FKTP-Biaya Tagih', 'Non-Kapitasi?', 'Kapitasi?', 'Dirujuk?', 'Jumlah Tindakan Non-Kapitasi', 'provinsi rujukan sama?', 'kab/kota rujukan sama?', 'FKTP-Weekend?', 'FKTP-Kode dan Nama Diagnosis']]

In [25]:
#Concatenate the two dataframes : 
data_out = pd.concat([X, df_numerik], axis=1)

In [29]:
data_out2 = pd.concat([df_y, df_numerik], axis=1)

In [27]:
data_out.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1733755 entries, 0 to 1733754
Columns: 124 entries, FKTP-Kepemilikan Faskes_MISSING to FKTP-Kode dan Nama Diagnosis
dtypes: int64(15), uint8(109)
memory usage: 378.6 MB

In [31]:
data_out2.to_csv('datasampel/one_hot_fktp_2.csv')

In [32]:
data_out.to_csv('datasampel/one_hot_fktp.csv')